#feign:
#  hystrix:
#    enabled: false
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderDB
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8203


